version: 2
jobs:
  build:
    branches:
      only:
        - gh-pages
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build 11ty
          command: yarn build
      - add_ssh_keys:
          fingerprints:
            - 'bb:75:f6:aa:46:d3:bb:51:de:ab:f9:8b:65:3c:cc:5b'
      - run:
          name: Deploy to GitHub Pages
          command: sh ./.circleci/deploy.sh
